### ISSUE TITLE
Bug with array alignment and "newline"

### ISSUE THREAD

**Issue by ncou** [VincentLanglet/Symfony3-custom-coding-standard#134]
Hi,

Nice piece of code ! Your sniffs files are really usefull.
 I found 2 small bugs in the ArrayDeclarationSniff when there is a line return in the declaration. And the phpcs fix command will fail and return an error code = 2 and the file is not fixed.

A)
<pre>$array = [
    'lonnnnnnggggg' => 'good',
    'short' 
                 => 'bad',
];</pre>

This exemple will not be correctly formated (and the fix command will fail), because the second item will not be considered as a new line because the test in the class (https://github.com/VincentLanglet/symfony-custom-coding-standard/blob/master/SymfonyCustom/Sniffs/Arrays/ArrayDeclarationSniff.php#L607) will check if the arrow is before or after the item based on the length, so it will report 3 spaces found but it should report "newline" found, for the function "fixWhitespaceBefore" to work correctly. I think you should use the 'line' property in the tokens array to confirm if it's a new line or not. Something like :

<pre>if ($tokens[$index['index']]['line'] !== $tokens[$index['arrow']]['line']) {
    $found = 'newline';
}</pre>

B)
<pre>$array = [
    'lonnnnnngggggg' => good,
    $ab .
    'second' => 'bad',
];</pre>

In this case the second item arrow should be aligned with the first item arrow. But the phpcs fix command fail and return an error code = 2.
I have no idear how to fix this :)

Keep up the godd work !!!

Let me know if it's not clear.

**Comment by VincentLanglet** [comment]
Hi @ncou ! Thanks for the report, and sorry for the delay.
I totally missed your issue, but I'm looking at it now.

**Comment by ncou** [comment]
Thanks 👍
